# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wandr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('picture_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=200)),
                ('picture', models.ImageField(upload_to='profile_images')),
            ],
        ),
    ]
