# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wandr', '0002_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
