# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wandr', '0003_picture_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='HaveBeenList',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wandr.UserProfile')),
            ],
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(upload_to='travel_images'),
        ),
    ]
